### ISSUE TITLE
Is it possible to reload the parameters of the best iteration in Antares

### ISSUE THREAD

**Issue by payementcha** [rte-antares-rpackage/antaresXpansion#21]
Is it possible to reload the parameters of the best iteration in Antares. It avoids to rewrite manually the best solution to launch a new study from it ? 

Thanks, 

Charles

**Comment by baptsegu** [comment]
Will be supported in next version
https://github.com/rte-antares-rpackage/antaresXpansion/commit/c3e3299c7dd6618c1efc4be7e5df9211bd61b7eb
